import type { Place } from "./types";

/**
 * Placeholder photography, sourced from Wikimedia Commons and re-encoded to WebP.
 * Every entry carries its author and licence in `image.credit`, rendered on /turkey/credits.
 *
 * To use your own photo for a place: drop your file at public/images/turkey/<id>.webp,
 * update `width`/`height`/`color` below, and delete that entry's `credit` block.
 * Once every credit block is gone the credits page disappears on its own.
 */
export const places: Place[] = [
  {
    id: "istanbul",
    name: "Istanbul",
    region: "marmara",
    area: "Istanbul",
    teaser: "Two continents, one skyline, and a ferry ride between them.",
    description: "The old city sits on a peninsula between the Golden Horn and the Sea of Marmara, stacked with mosques, palaces and markets. Most first trips to Turkey start here, and a lot of people finish wishing they had given it more days.",
    highlights: [
      "Bosphorus ferry between Europe and Asia",
      "Sultanahmet on foot",
      "Rooftop dinners over the Golden Horn",
      "Ferry to Kadıköy for the food streets",
    ],
    experiences: ["city", "food", "culture", "boat"],
    season: "year-round",
    window: "Good all year. Spring and autumn are the most comfortable for walking.",
    image: {
      src: "/images/turkey/istanbul.webp",
      width: 927,
      height: 618,
      color: "#71695c",
      credit: { author: "Hunanuk", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Historical_peninsula_and_modern_skyline_of_Istanbul.jpg" },
    },
  },
  {
    id: "hagia-sophia",
    name: "Hagia Sophia",
    region: "marmara",
    area: "Istanbul",
    teaser: "Fifteen centuries under one dome.",
    description: "Built as a cathedral in 537, later a mosque, then a museum, and a mosque again. Standing under the dome is the part nobody manages to describe properly afterwards.",
    highlights: [
      "The main dome and upper gallery",
      "Byzantine mosaics",
      "Sunset in the square between Hagia Sophia and the Blue Mosque",
    ],
    experiences: ["culture", "ruins", "city"],
    season: "year-round",
    window: "Open all year. Go early in the morning to avoid the queue.",
    image: {
      src: "/images/turkey/hagia-sophia.webp",
      width: 1161,
      height: 774,
      color: "#7d878f",
      credit: { author: "Adli Wahid", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Hagia_Sophia_(228968325).jpeg" },
    },
  },
  {
    id: "bosphorus",
    name: "The Bosphorus",
    region: "marmara",
    area: "Istanbul",
    teaser: "The strait that splits a city and joins two seas.",
    description: "A full day can go on the water here: fishing villages, wooden waterfront houses, fortresses, and the bridges lit up after dark. Public ferries are cheap and private boats are easy to arrange.",
    highlights: [
      "Full cruise up to Anadolu Kavağı",
      "Private sunset boat",
      "Ortaköy and Bebek waterfront",
      "Fish sandwich at Eminönü",
    ],
    experiences: ["boat", "city", "food"],
    season: "year-round",
    window: "Runs all year. Summer evenings are the classic time.",
    image: {
      src: "/images/turkey/bosphorus.webp",
      width: 1200,
      height: 800,
      color: "#6e7264",
      credit: { author: "Huseyinakbas63", license: "CC BY 4.0", source: "https://commons.wikimedia.org/wiki/File:Bosphorus_Bridge_(1973)_in_Istanbul.jpg" },
    },
  },
  {
    id: "princes-islands",
    name: "Princes' Islands",
    region: "marmara",
    area: "Sea of Marmara",
    teaser: "Car free islands an hour from the city.",
    description: "Nine islands in the Sea of Marmara where motor traffic is banned. Wooden mansions, pine woods, swimming coves and bicycles. Büyükada is the largest and the easiest to do in a day.",
    highlights: [
      "Ferry from Kabataş or Bostancı",
      "Cycling around Büyükada",
      "Swimming coves in summer",
      "Seafood lunch by the harbour",
    ],
    experiences: ["boat", "beach", "hike", "food"],
    season: "seasonal",
    window: "Best May to October.",
    note: "Quiet and often cold out of season, with fewer ferries and many places closed.",
    image: {
      src: "/images/turkey/princes-islands.webp",
      width: 1080,
      height: 720,
      color: "#5d7288",
      credit: { author: "Metuboy", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:BuyukadaMainSquare.jpg" },
    },
  },
  {
    id: "bursa-uludag",
    name: "Bursa and Uludağ",
    region: "marmara",
    area: "Bursa",
    teaser: "The first Ottoman capital, with a ski mountain above it.",
    description: "Bursa has silk markets, thermal baths and early Ottoman mosques. Above it, Uludağ becomes Turkey's best known ski resort once the snow arrives, reachable by cable car from the city.",
    highlights: [
      "Cable car up Uludağ",
      "Skiing and snowboarding",
      "Thermal baths at Çekirge",
      "Iskender kebab where it was invented",
    ],
    experiences: ["snow", "thermal", "food", "culture"],
    season: "year-round",
    window: "The city is good all year. Skiing usually runs late December to March.",
    note: "Snow cover varies from year to year, so ski dates get confirmed closer to the time.",
    image: {
      src: "/images/turkey/bursa-uludag.webp",
      width: 1200,
      height: 800,
      color: "#a4aab6",
      credit: { author: "Kartal Arikan", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Uluda%C4%9F_-_Olympos_Misios.jpg" },
    },
  },
  {
    id: "troy",
    name: "Troy",
    region: "marmara",
    area: "Çanakkale",
    teaser: "The city from the Iliad, dug out of a mound.",
    description: "Nine cities stacked on the same site across three thousand years. The wooden horse in the grounds is a modern replica, and it is still the photo everyone takes.",
    highlights: [
      "Walking the excavated layers",
      "The horse replica",
      "Çanakkale waterfront",
      "Paired with Gallipoli in one trip",
    ],
    experiences: ["ruins", "culture"],
    season: "year-round",
    window: "Open all year. Shade is scarce, so summer midday is hard work.",
    image: {
      src: "/images/turkey/troy.webp",
      width: 1086,
      height: 724,
      color: "#687171",
      credit: { author: "Radosław Botev", license: "CC BY 3.0 pl", source: "https://commons.wikimedia.org/wiki/File:Trojan_Horse_in_Troy_National_Park.jpg" },
    },
  },
  {
    id: "cappadocia",
    name: "Cappadocia",
    region: "cappadocia",
    area: "Nevşehir",
    teaser: "Balloons over a valley carved out of soft rock.",
    description: "Volcanic ash hardened into towers and cones, and people then hollowed them into homes, churches and entire underground cities. Sunrise here, with a few hundred balloons in the air, is the picture most people have in mind when they think of Turkey.",
    highlights: [
      "Sunrise hot air balloon flight",
      "Göreme open air museum",
      "Cave hotels",
      "Red and Rose valley walk at sunset",
      "Pottery in Avanos",
    ],
    experiences: ["balloon", "hike", "ruins", "culture"],
    season: "year-round",
    window: "Good all year. Balloons fly most often from April to June and September to October.",
    note: "Balloon flights get cancelled for wind or fog at short notice. That is a safety call, not a service failure, so we build spare days into trips wherever we can.",
    image: {
      src: "/images/turkey/cappadocia.webp",
      width: 1200,
      height: 800,
      color: "#8a8c90",
      credit: { author: "Arian Zwegers from Brussels, Belgium", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Cappadocia_balloon_trip,_Ortahisar_Castle_(11893715185).jpg" },
    },
  },
  {
    id: "uchisar",
    name: "Uçhisar",
    region: "cappadocia",
    area: "Nevşehir",
    teaser: "A whole village tunnelled into one rock.",
    description: "The highest point in Cappadocia, a castle rock riddled with rooms and passages. The view from the top takes in most of the valleys at once.",
    highlights: [
      "Climb to the castle top",
      "Pigeon Valley walk down to Göreme",
      "Sunset over the valleys",
    ],
    experiences: ["hike", "ruins"],
    season: "year-round",
    window: "Open all year.",
    image: {
      src: "/images/turkey/uchisar.webp",
      width: 1200,
      height: 800,
      color: "#84929f",
      credit: { author: "Bernard Gagnon", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:U%C3%A7hisar,_Cappadocia_01.jpg" },
    },
  },
  {
    id: "derinkuyu",
    name: "Derinkuyu",
    region: "cappadocia",
    area: "Nevşehir",
    teaser: "A city for twenty thousand people, underground.",
    description: "Eighteen levels cut down into the rock, with stables, chapels, wells, ventilation shafts, and stone doors that rolled shut from the inside. It was built to hide in, and it worked.",
    highlights: [
      "Descending through the levels",
      "Ventilation shafts and rolling stone doors",
      "Paired with Kaymaklı nearby",
    ],
    experiences: ["ruins", "culture"],
    season: "year-round",
    window: "Open all year, and a good option on a hot or wet day.",
    note: "Passages are narrow and low in places. Worth telling us in advance if that is a problem for anyone in your group.",
    image: {
      src: "/images/turkey/derinkuyu.webp",
      width: 1200,
      height: 800,
      color: "#333027",
      credit: { author: "Nevit Dilmen (talk)", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Derinkuyu_Underground_City_9910_Nevit.jpg" },
    },
  },
  {
    id: "ihlara",
    name: "Ihlara Valley",
    region: "cappadocia",
    area: "Aksaray",
    teaser: "A green canyon with churches cut into the walls.",
    description: "A river gorge running about fourteen kilometres, a hundred metres deep, lined with poplars and rock churches. It is the cool, shaded side of Cappadocia.",
    highlights: [
      "Walking the gorge floor",
      "Byzantine rock churches",
      "Riverside tea gardens",
      "Selime monastery at the far end",
    ],
    experiences: ["hike", "ruins"],
    season: "seasonal",
    window: "Best April to October.",
    note: "The path can be muddy or icy in winter.",
    image: {
      src: "/images/turkey/ihlara.webp",
      width: 1200,
      height: 800,
      color: "#605e4d",
      credit: { author: "Tevfik Teker", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Ihlara_Valley_-_panoramio_(31).jpg" },
    },
  },
  {
    id: "konya",
    name: "Konya",
    region: "cappadocia",
    area: "Konya",
    teaser: "Where Rumi is buried and the dervishes still turn.",
    description: "A quiet, serious city built around the Mevlâna museum and its turquoise dome. The whirling ceremony is a form of worship rather than a performance, and it reads that way when you watch it.",
    highlights: [
      "Mevlâna museum and tomb",
      "Sema ceremony",
      "Seljuk architecture",
      "Şeb-i Arûs in December",
    ],
    experiences: ["culture", "city"],
    season: "year-round",
    window: "Good all year. The Şeb-i Arûs ceremonies fall in the second week of December.",
    image: {
      src: "/images/turkey/konya.webp",
      width: 1200,
      height: 800,
      color: "#454560",
      credit: { author: "Emad Nemati", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Maulana_Jelaledin_Muhammad_Rumi_in_konya.jpg" },
    },
  },
  {
    id: "ankara",
    name: "Ankara",
    region: "cappadocia",
    area: "Ankara",
    teaser: "The capital, and the museum that explains the rest of the country.",
    description: "Anıtkabir, the mausoleum of Atatürk, sits on a hill above the city and is worth the time. The Museum of Anatolian Civilisations nearby holds the Hittite and Neolithic material that puts every other site in context.",
    highlights: [
      "Anıtkabir",
      "Museum of Anatolian Civilisations",
      "Ankara castle and the old quarter",
    ],
    experiences: ["culture", "city", "ruins"],
    season: "year-round",
    window: "Good all year.",
    image: {
      src: "/images/turkey/ankara.webp",
      width: 1200,
      height: 800,
      color: "#6d6e6f",
      credit: { author: "William Neuheisel from DC, US", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Ataturk%27s_Mausoleum_(6225341313).jpg" },
    },
  },
  {
    id: "ephesus",
    name: "Ephesus",
    region: "aegean",
    area: "İzmir",
    teaser: "Marble streets, and a library front still standing.",
    description: "One of the best preserved ancient cities anywhere. You walk down a marble main street past the terraced houses to the Library of Celsus, then on to a theatre that held twenty five thousand people.",
    highlights: [
      "Library of Celsus",
      "The great theatre",
      "Terrace houses",
      "House of the Virgin Mary nearby",
    ],
    experiences: ["ruins", "culture"],
    season: "year-round",
    window: "Open all year. Early morning is best in summer.",
    note: "There is very little shade. In July and August, go at opening time.",
    image: {
      src: "/images/turkey/ephesus.webp",
      width: 1200,
      height: 800,
      color: "#777574",
      credit: { author: "Benh LIEU SONG", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Ephesus_Celsus_Library_Fa%C3%A7ade.jpg" },
    },
  },
  {
    id: "pamukkale",
    name: "Pamukkale",
    region: "aegean",
    area: "Denizli",
    teaser: "White terraces of calcium, filled with warm water.",
    description: "Hot mineral springs have run down this hillside for thousands of years, leaving white travertine basins behind. The Roman spa city of Hierapolis sits directly on top of it.",
    highlights: [
      "Walking barefoot on the terraces",
      "Hierapolis ruins and theatre",
      "Cleopatra's antique pool",
      "Sunset from the upper terraces",
    ],
    experiences: ["thermal", "ruins", "hike"],
    season: "year-round",
    window: "Good all year. The water stays warm even in winter.",
    image: {
      src: "/images/turkey/pamukkale.webp",
      width: 1200,
      height: 800,
      color: "#9da3a9",
      credit: { author: "Biologg", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Pamukkale,_Denizli_2026_68.jpg" },
    },
  },
  {
    id: "sirince",
    name: "Şirince",
    region: "aegean",
    area: "İzmir",
    teaser: "A hill village that makes fruit wine.",
    description: "Old stone and plaster houses on a slope above Selçuk, with a market street, small wineries, and views over olive groves. An easy add on to an Ephesus day.",
    highlights: [
      "Fruit wine tasting",
      "Village market",
      "Breakfast on a terrace",
      "Paired with Ephesus",
    ],
    experiences: ["food", "culture"],
    season: "year-round",
    window: "Good all year, busiest at weekends.",
    image: {
      src: "/images/turkey/sirince.webp",
      width: 730,
      height: 487,
      color: "#607576",
      credit: { author: "Cheyrek", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Sirince_Overview_2012.jpg" },
    },
  },
  {
    id: "bodrum",
    name: "Bodrum",
    region: "aegean",
    area: "Muğla",
    teaser: "A crusader castle, a marina, and boats leaving all day.",
    description: "The castle of St Peter guards the harbour, and the peninsula behind it holds the bays and beach clubs. It is also the usual starting point for a gulet cruise down the coast.",
    highlights: [
      "Castle and Museum of Underwater Archaeology",
      "Gulet day trips",
      "Bays around the peninsula",
      "Nightlife in town",
    ],
    experiences: ["boat", "beach", "ruins", "city"],
    season: "seasonal",
    window: "Best May to October.",
    note: "Much of the town closes down over winter.",
    image: {
      src: "/images/turkey/bodrum.webp",
      width: 1200,
      height: 800,
      color: "#76848a",
      credit: { author: "Horvat", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:Turkey_Bodrum_Castle_Mosque.jpg" },
    },
  },
  {
    id: "alacati",
    name: "Alaçatı",
    region: "aegean",
    area: "İzmir",
    teaser: "Stone streets, bougainvillea, and reliable wind.",
    description: "A restored village near Çeşme that turned into one of Turkey's best looking small towns. The bay next to it is a well known windsurfing spot, because the wind almost always shows up.",
    highlights: [
      "Windsurfing and kitesurfing",
      "Stone street cafés",
      "Saturday market",
      "Beach clubs at Çeşme",
    ],
    experiences: ["beach", "food", "city"],
    season: "seasonal",
    window: "Best May to September.",
    note: "Quiet out of season, with many places shut.",
    image: {
      src: "/images/turkey/alacati.webp",
      width: 1200,
      height: 800,
      color: "#6f665e",
      credit: { author: "Write it Right UAE", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Alacati_Streets.jpg" },
    },
  },
  {
    id: "pergamon",
    name: "Pergamon",
    region: "aegean",
    area: "İzmir",
    teaser: "A theatre built into a cliff at an alarming angle.",
    description: "The acropolis sits high above modern Bergama, reached by cable car. Its theatre is the steepest of the ancient world, and the Asclepion below was one of antiquity's great medical centres.",
    highlights: [
      "Acropolis by cable car",
      "The steep theatre",
      "Asclepion healing centre",
      "Red Basilica in town",
    ],
    experiences: ["ruins", "culture"],
    season: "year-round",
    window: "Open all year.",
    image: {
      src: "/images/turkey/pergamon.webp",
      width: 1200,
      height: 800,
      color: "#9d9d92",
      credit: { author: "Adam Jones from Kelowna, BC, Canada", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:Acropolis_-_Bergama_(Pergamon)_-_Turkey_-_10_(5747249729).jpg" },
    },
  },
  {
    id: "antalya-kaleici",
    name: "Antalya Kaleiçi",
    region: "turquoise",
    area: "Antalya",
    teaser: "An old harbour ringed by Roman walls.",
    description: "The old town sits inside its walls above a small marina, with Ottoman houses now run as guesthouses. The rest of Antalya spreads along the cliffs, with beaches at either end.",
    highlights: [
      "Old harbour and boat trips",
      "Hadrian's Gate",
      "Konyaaltı and Lara beaches",
      "Antalya Archaeological Museum",
    ],
    experiences: ["city", "beach", "boat", "ruins"],
    season: "year-round",
    window: "Good all year. Swimming is comfortable roughly May to October.",
    image: {
      src: "/images/turkey/antalya-kaleici.webp",
      width: 1200,
      height: 800,
      color: "#67898a",
      credit: { author: "REHBER0770", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Antalya_kalei%C3%A7i_2.jpg" },
    },
  },
  {
    id: "oludeniz",
    name: "Ölüdeniz",
    region: "turquoise",
    area: "Muğla",
    teaser: "The lagoon you have already seen a photo of.",
    description: "A sheltered blue lagoon under Babadağ mountain. Paragliders launch from nearly two thousand metres above it and land on the beach, which is the main reason a lot of people come.",
    highlights: [
      "Tandem paragliding from Babadağ",
      "The Blue Lagoon",
      "Butterfly Valley by boat",
      "Boat trips along the coast",
    ],
    experiences: ["beach", "boat", "hike"],
    season: "seasonal",
    window: "Best May to October. Paragliding depends on the wind.",
    note: "Flights get grounded when the wind is wrong. It is normal, and worth allowing a spare day for.",
    image: {
      src: "/images/turkey/oludeniz.webp",
      width: 1200,
      height: 800,
      color: "#36748c",
      credit: { author: "Andrzej Szkopiński", license: "CC BY 3.0", source: "https://commons.wikimedia.org/wiki/File:Paragliding_view_oludeniz_-_panoramio_(2).jpg" },
    },
  },
  {
    id: "kekova",
    name: "Kekova",
    region: "turquoise",
    area: "Antalya",
    teaser: "A sunken town you look down into from a boat.",
    description: "An earthquake dropped part of an ancient settlement into the sea here. Staircases and walls run straight down under clear water, and the village of Kaleköy above it has a castle and Lycian tombs.",
    highlights: [
      "Boat over the sunken city",
      "Kaleköy castle and rock tombs",
      "Sea kayaking",
      "Swimming stops in the bays",
    ],
    experiences: ["boat", "ruins", "beach"],
    season: "seasonal",
    window: "Best May to October.",
    note: "Swimming directly over the ruins is restricted, to protect them.",
    image: {
      src: "/images/turkey/kekova.webp",
      width: 1200,
      height: 800,
      color: "#7d888c",
      credit: { author: "Bjørn Christian Tørrissen", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Kekova_island_and_Kalekoey_village.jpg" },
    },
  },
  {
    id: "kas",
    name: "Kaş",
    region: "turquoise",
    area: "Antalya",
    teaser: "A small diving town on a steep hillside.",
    description: "Kaş drops down to a tiny harbour, with a Hellenistic theatre on the edge of town. It is the diving base for this stretch of coast, and quieter than the bigger resorts.",
    highlights: [
      "Scuba diving and freediving",
      "Sea kayaking to Kekova",
      "The hillside theatre at sunset",
      "Day boat to Meis",
    ],
    experiences: ["boat", "beach", "ruins"],
    season: "seasonal",
    window: "Best May to October.",
    image: {
      src: "/images/turkey/kas.webp",
      width: 1200,
      height: 800,
      color: "#667472",
      credit: { author: "Luc Coekaerts", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:View_Kas.jpg" },
    },
  },
  {
    id: "aspendos",
    name: "Aspendos",
    region: "turquoise",
    area: "Antalya",
    teaser: "A Roman theatre that still fills up for concerts.",
    description: "Close to intact after eighteen centuries, seating around fifteen thousand. The acoustics are good enough that it is still used for opera and ballet in summer.",
    highlights: [
      "The theatre",
      "Summer opera and ballet festival",
      "Roman aqueduct nearby",
      "Paired with Side and Perge",
    ],
    experiences: ["ruins", "culture"],
    season: "year-round",
    window: "Open all year. The festival season usually falls in September.",
    image: {
      src: "/images/turkey/aspendos.webp",
      width: 1200,
      height: 800,
      color: "#8b9793",
      credit: { author: "Dosseman", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Aspendos_Basilica_4728.jpg" },
    },
  },
  {
    id: "duden",
    name: "Düden Waterfalls",
    region: "turquoise",
    area: "Antalya",
    teaser: "A waterfall that drops straight into the sea.",
    description: "The Düden river reaches the Mediterranean by falling off a cliff at the edge of Antalya. There is an upper falls inland that you can walk behind, and a lower falls best seen from a boat.",
    highlights: [
      "Lower falls from a boat",
      "Walking behind the upper falls",
      "Park and tea gardens",
    ],
    experiences: ["hike", "boat"],
    season: "year-round",
    window: "Good all year, fullest in spring.",
    image: {
      src: "/images/turkey/duden.webp",
      width: 1200,
      height: 800,
      color: "#4b4a3f",
      credit: { author: "Saffron Blaze", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Upper_Duden_Falls.jpg" },
    },
  },
  {
    id: "koprulu",
    name: "Köprülü Canyon",
    region: "turquoise",
    area: "Antalya",
    teaser: "Cold green water and a rafting run.",
    description: "A canyon in the Taurus mountains with a Roman bridge across it and a fast, cold river underneath. The standard rafting run is beginner friendly, and the water is a shock in the best way.",
    highlights: [
      "White water rafting",
      "The Roman bridge",
      "Canyon walks",
      "Trout lunch by the river",
    ],
    experiences: ["hike", "boat"],
    season: "seasonal",
    window: "Rafting usually runs April to October.",
    note: "Water level and safety depend on rainfall and on dam release schedules.",
    image: {
      src: "/images/turkey/koprulu.webp",
      width: 1200,
      height: 800,
      color: "#444a3b",
      credit: { author: "Gökhannergiz at Turkish Wikipedia", license: "Public domain", source: "https://commons.wikimedia.org/wiki/File:K%C3%B6pr%C3%BCl%C3%BC_Kanyon.JPG" },
    },
  },
  {
    id: "uzungol",
    name: "Uzungöl",
    region: "blacksea",
    area: "Trabzon",
    teaser: "A lake in a fold of green mountains.",
    description: "A long lake in the Trabzon highlands, ringed by steep forested slopes that spend much of the day in cloud. It is the picture people mean by the Turkish Black Sea.",
    highlights: [
      "Walking around the lake",
      "Highland plateaus above the valley",
      "Local trout and cornbread",
      "Mist in the early morning",
    ],
    experiences: ["hike", "food"],
    season: "seasonal",
    window: "Best June to September.",
    note: "Roads into the higher plateaus can close with snow in winter.",
    image: {
      src: "/images/turkey/uzungol.webp",
      width: 1200,
      height: 800,
      color: "#667779",
      credit: { author: "Ozbakanelwan", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Uzung%C3%B6l,_Trabzon.jpg" },
    },
  },
  {
    id: "sumela",
    name: "Sumela Monastery",
    region: "blacksea",
    area: "Trabzon",
    teaser: "A monastery stuck to a cliff face.",
    description: "Built into a rock wall three hundred metres above a forested valley, founded in the fourth century. Frescoes cover the rock church inside.",
    highlights: [
      "The cliff approach",
      "Rock church frescoes",
      "Altındere valley forest",
    ],
    experiences: ["culture", "hike", "ruins"],
    season: "seasonal",
    window: "Best May to October.",
    note: "Access can close in winter or for restoration work, so we check before committing to dates.",
    image: {
      src: "/images/turkey/sumela.webp",
      width: 759,
      height: 506,
      color: "#726857",
      credit: { author: "Bjørn Christian Tørrissen", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Sumela_From_Across_Valley.JPG" },
    },
  },
  {
    id: "ayder",
    name: "Ayder",
    region: "blacksea",
    area: "Rize",
    teaser: "Highland pasture, hot springs and mist.",
    description: "A plateau village above Çamlıhemşin with wooden houses, thermal baths, and cloud that rolls through most afternoons. The Kaçkar mountains start just behind it.",
    highlights: [
      "Thermal springs",
      "Highland plateaus by jeep",
      "Kaçkar trekking",
      "Muhlama and local honey",
    ],
    experiences: ["thermal", "hike", "food"],
    season: "seasonal",
    window: "Best June to September.",
    note: "Snow closes the higher plateaus for much of the year.",
    image: {
      src: "/images/turkey/ayder.webp",
      width: 1200,
      height: 800,
      color: "#74a042",
      credit: { author: "Dr. Zeynel Cebeci", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Ayder_Yaylasi_@_Rize-Turkey.JPG" },
    },
  },
  {
    id: "safranbolu",
    name: "Safranbolu",
    region: "blacksea",
    area: "Karabük",
    teaser: "An Ottoman town preserved more or less whole.",
    description: "Timber framed merchant houses along cobbled streets, protected as a UNESCO site. Many of the houses are now small hotels, so you sleep inside the thing you came to see.",
    highlights: [
      "Staying in a restored konak",
      "Old bazaar and blacksmiths",
      "Turkish delight and saffron",
      "Hıdırlık hill viewpoint",
    ],
    experiences: ["culture", "food", "city"],
    season: "year-round",
    window: "Good all year. It looks best under snow, or in autumn.",
    image: {
      src: "/images/turkey/safranbolu.webp",
      width: 1200,
      height: 800,
      color: "#867673",
      credit: { author: "Ray Swi-hymn", license: "CC BY-SA 2.0", source: "https://commons.wikimedia.org/wiki/File:20180107_Safranbolu_1945_(39101010504).jpg" },
    },
  },
  {
    id: "amasra",
    name: "Amasra",
    region: "blacksea",
    area: "Bartın",
    teaser: "A small port on two bays.",
    description: "A Black Sea town on a headland, with a Genoese castle, an island joined by a Roman bridge, and fish restaurants along the water. Wood carving is the local trade.",
    highlights: [
      "Castle walls and the island",
      "Fish lunch on the harbour",
      "Coastal drive towards Sinop",
      "Wood carving workshops",
    ],
    experiences: ["boat", "food", "city"],
    season: "seasonal",
    window: "Best May to September.",
    image: {
      src: "/images/turkey/amasra.webp",
      width: 1080,
      height: 720,
      color: "#7e7f83",
      credit: { author: "Jorge Franganillo", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Amasra_(9310207038).jpg" },
    },
  },
  {
    id: "yedigoller",
    name: "Yedigöller",
    region: "blacksea",
    area: "Bolu",
    teaser: "Seven lakes that turn every colour in autumn.",
    description: "A national park north of Bolu where seven lakes sit in beech and oak forest. It is deliberately low key: forest tracks, water, and no crowds outside the autumn peak.",
    highlights: [
      "Autumn colour in late October",
      "Forest walks between the lakes",
      "Photography",
      "Camping and cabins",
    ],
    experiences: ["hike"],
    season: "seasonal",
    window: "Best late September to early November for colour.",
    note: "Peak colour shifts by a week or two each year with the weather.",
    image: {
      src: "/images/turkey/yedigoller.webp",
      width: 1200,
      height: 800,
      color: "#596d69",
      credit: { author: "A.Savin", license: "FAL", source: "https://commons.wikimedia.org/wiki/File:TR_Yedig%C3%B6ller_asv2021-10_img16.jpg" },
    },
  },
  {
    id: "mardin",
    name: "Mardin",
    region: "anatolia",
    area: "Mardin",
    teaser: "A honey coloured city looking out over Mesopotamia.",
    description: "Terraced stone houses stacked down a hillside above a plain that runs south to Syria. Arabic, Kurdish, Turkish and Syriac have all been spoken here for a very long time.",
    highlights: [
      "Old city stone streets",
      "Deyrulzafaran monastery",
      "Copper and silver workshops",
      "Sunset over the plain",
    ],
    experiences: ["culture", "city", "food"],
    season: "year-round",
    window: "Best in spring and autumn.",
    note: "July and August regularly pass forty degrees.",
    image: {
      src: "/images/turkey/mardin.webp",
      width: 1200,
      height: 800,
      color: "#b4aa9f",
      credit: { author: "Hamdigumus", license: "CC0", source: "https://commons.wikimedia.org/wiki/File:Eski_Mardin_5.jpg" },
    },
  },
  {
    id: "gobeklitepe",
    name: "Göbekli Tepe",
    region: "anatolia",
    area: "Şanlıurfa",
    teaser: "The oldest known temple, by about seven thousand years.",
    description: "Carved stone pillars set in circles around 9500 BC, raised by people who had not yet started farming. It moved the accepted start date of monumental architecture, and it is still being excavated.",
    highlights: [
      "The excavated enclosures",
      "Carved animal reliefs",
      "Şanlıurfa museum with the original finds",
      "Paired with Balıklıgöl",
    ],
    experiences: ["ruins", "culture"],
    season: "year-round",
    window: "Best in spring and autumn.",
    note: "The site itself is under a shelter, but the surroundings are hot and open in summer.",
    image: {
      src: "/images/turkey/gobeklitepe.webp",
      width: 1200,
      height: 800,
      color: "#7d7772",
      credit: { author: "Teomancimit", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:G%C3%B6bekli_Tepe,_Urfa.jpg" },
    },
  },
  {
    id: "nemrut",
    name: "Mount Nemrut",
    region: "anatolia",
    area: "Adıyaman",
    teaser: "Giant stone heads on a summit, at sunrise.",
    description: "A first century BC king built his own tomb sanctuary at two thousand metres and lined it with colossal statues. Earthquakes took the heads off, and they now sit on the ground looking outward.",
    highlights: [
      "Sunrise on the east terrace",
      "The toppled heads",
      "Arsameia and the Cendere bridge",
      "Adiyaman as a base",
    ],
    experiences: ["ruins", "hike", "culture"],
    season: "seasonal",
    window: "Usually accessible May to October.",
    note: "The summit road closes with snow in winter, and it is cold at the top even in summer. Bring a jacket for sunrise.",
    image: {
      src: "/images/turkey/nemrut.webp",
      width: 1200,
      height: 800,
      color: "#8a8380",
      credit: { author: "Klearchos Kapoutsis from Santorini, Greece", license: "CC BY 2.0", source: "https://commons.wikimedia.org/wiki/File:Mount_Nemrut_-_Apollo_and_Heracles_Artagnes_Ares_(4961939940).jpg" },
    },
  },
  {
    id: "ani",
    name: "Ani",
    region: "anatolia",
    area: "Kars",
    teaser: "A ruined medieval capital on a closed border.",
    description: "Once a Silk Road city of a hundred thousand people, now empty churches and walls on a grass plateau above a gorge, with Armenia on the far side. There is nothing else quite like the silence.",
    highlights: [
      "Cathedral and Church of the Redeemer",
      "The city walls",
      "The gorge and the border view",
      "Kars as a base",
    ],
    experiences: ["ruins", "culture", "hike"],
    season: "seasonal",
    window: "Best May to October.",
    note: "Winters at Kars are severe, regularly well below freezing.",
    image: {
      src: "/images/turkey/ani.webp",
      width: 1165,
      height: 777,
      color: "#63686c",
      credit: { author: "Engin Tavlı", license: "CC BY-SA 4.0", source: "https://commons.wikimedia.org/wiki/File:Ani_Harabeleri_2.jpg" },
    },
  },
  {
    id: "halfeti",
    name: "Halfeti",
    region: "anatolia",
    area: "Şanlıurfa",
    teaser: "A half drowned town you visit by boat.",
    description: "A dam raised the Euphrates and put part of Halfeti under water. You take a boat out over the old village, past a minaret standing up out of the river, and on to Rumkale.",
    highlights: [
      "Boat over the flooded village",
      "The submerged minaret",
      "Rumkale fortress",
      "Black roses in season",
    ],
    experiences: ["boat", "culture"],
    season: "seasonal",
    window: "Best March to June, and September to November.",
    note: "The water level changes with the dam, so what is visible varies.",
    image: {
      src: "/images/turkey/halfeti.webp",
      width: 1200,
      height: 800,
      color: "#7a807d",
      credit: { author: "Bernard Gagnon", license: "CC BY-SA 3.0", source: "https://commons.wikimedia.org/wiki/File:Halfeti_on_the_Euphrates.jpg" },
    },
  },
];
